/*
* Copyright (c) 2021 Citrix Systems, Inc.
*
*   Licensed under the Apache License, Version 2.0 (the "License");
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

package snmp


type Snmpstats struct {
	/**
	* Clear the statsistics / counters
	*/
	Clearstats string `json:"clearstats,omitempty"`
	Snmptotrxpkts uint64 `json:"snmptotrxpkts,omitempty"`
	/**
	* SNMP packets received.
	*/
	Snmprxpktsrate float64 `json:"snmprxpktsrate,omitempty"`
	Snmptottxpkts uint64 `json:"snmptottxpkts,omitempty"`
	/**
	* SNMP packets transmitted.
	*/
	Snmptxpktsrate float64 `json:"snmptxpktsrate,omitempty"`
	Snmptotgetreqs uint64 `json:"snmptotgetreqs,omitempty"`
	/**
	* SNMP Get-Request PDUs that have been accepted and processed.
	*/
	Snmpgetreqsrate float64 `json:"snmpgetreqsrate,omitempty"`
	Snmptotgetnextreqs uint64 `json:"snmptotgetnextreqs,omitempty"`
	/**
	* SNMP Get-Next PDUs that have been accepted and processed.
	*/
	Snmpgetnextreqsrate float64 `json:"snmpgetnextreqsrate,omitempty"`
	Snmptotgetbulkreqs uint64 `json:"snmptotgetbulkreqs,omitempty"`
	/**
	* SNMP Get-Bulk PDUs that have been accepted and processed.
	*/
	Snmpgetbulkreqsrate float64 `json:"snmpgetbulkreqsrate,omitempty"`
	Snmptotresponses uint64 `json:"snmptotresponses,omitempty"`
	/**
	* SNMP Get-Response PDUs that have been generated by the Citrix ADC.
	*/
	Snmpresponsesrate float64 `json:"snmpresponsesrate,omitempty"`
	Snmptottraps uint64 `json:"snmptottraps,omitempty"`
	Snmptoterrreqdropped uint64 `json:"snmptoterrreqdropped,omitempty"`
	Snmptotparseerrs uint64 `json:"snmptotparseerrs,omitempty"`
	Snmptotbadversions uint64 `json:"snmptotbadversions,omitempty"`
	Snmptotbadcommname uint64 `json:"snmptotbadcommname,omitempty"`
	Snmptotbadcommuse uint64 `json:"snmptotbadcommuse,omitempty"`
	Snmpunsupportedsecuritylevel uint64 `json:"snmpunsupportedsecuritylevel,omitempty"`
	Snmpnotintimewindow uint64 `json:"snmpnotintimewindow,omitempty"`
	Snmpunknownusername uint64 `json:"snmpunknownusername,omitempty"`
	Snmpunknownengineids uint64 `json:"snmpunknownengineids,omitempty"`
	Snmpwrongdigests uint64 `json:"snmpwrongdigests,omitempty"`
	Snmpdecryptionerrors uint64 `json:"snmpdecryptionerrors,omitempty"`

}
