/*
* Copyright (c) 2021 Citrix Systems, Inc.
*
*   Licensed under the Apache License, Version 2.0 (the "License");
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
 */

package snmp

type Snmpstats struct {
	/**
	* Clear the statsistics / counters
	 */
	Clearstats    string `json:"clearstats,omitempty"`
	Snmptotrxpkts int    `json:"snmptotrxpkts,omitempty"`
	/**
	* SNMP packets received.
	 */
	Snmprxpktsrate float64 `json:"snmprxpktsrate,omitempty"`
	Snmptottxpkts  int     `json:"snmptottxpkts,omitempty"`
	/**
	* SNMP packets transmitted.
	 */
	Snmptxpktsrate float64 `json:"snmptxpktsrate,omitempty"`
	Snmptotgetreqs int     `json:"snmptotgetreqs,omitempty"`
	/**
	* SNMP Get-Request PDUs that have been accepted and processed.
	 */
	Snmpgetreqsrate    float64 `json:"snmpgetreqsrate,omitempty"`
	Snmptotgetnextreqs int     `json:"snmptotgetnextreqs,omitempty"`
	/**
	* SNMP Get-Next PDUs that have been accepted and processed.
	 */
	Snmpgetnextreqsrate float64 `json:"snmpgetnextreqsrate,omitempty"`
	Snmptotgetbulkreqs  int     `json:"snmptotgetbulkreqs,omitempty"`
	/**
	* SNMP Get-Bulk PDUs that have been accepted and processed.
	 */
	Snmpgetbulkreqsrate float64 `json:"snmpgetbulkreqsrate,omitempty"`
	Snmptotresponses    int     `json:"snmptotresponses,omitempty"`
	/**
	* SNMP Get-Response PDUs that have been generated by the Citrix ADC.
	 */
	Snmpresponsesrate            float64 `json:"snmpresponsesrate,omitempty"`
	Snmptottraps                 int     `json:"snmptottraps,omitempty"`
	Snmptoterrreqdropped         int     `json:"snmptoterrreqdropped,omitempty"`
	Snmptotparseerrs             int     `json:"snmptotparseerrs,omitempty"`
	Snmptotbadversions           int     `json:"snmptotbadversions,omitempty"`
	Snmptotbadcommname           int     `json:"snmptotbadcommname,omitempty"`
	Snmptotbadcommuse            int     `json:"snmptotbadcommuse,omitempty"`
	Snmpunsupportedsecuritylevel int     `json:"snmpunsupportedsecuritylevel,omitempty"`
	Snmpnotintimewindow          int     `json:"snmpnotintimewindow,omitempty"`
	Snmpunknownusername          int     `json:"snmpunknownusername,omitempty"`
	Snmpunknownengineids         int     `json:"snmpunknownengineids,omitempty"`
	Snmpwrongdigests             int     `json:"snmpwrongdigests,omitempty"`
	Snmpdecryptionerrors         int     `json:"snmpdecryptionerrors,omitempty"`
}
