/*
* Copyright (c) 2021 Citrix Systems, Inc.
*
*   Licensed under the Apache License, Version 2.0 (the "License");
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
 */

package stat

type Appfwstats struct {
	/**
	* Clear the statsistics / counters
	 */
	Clearstats          string `json:"clearstats,omitempty"`
	Appfirewalltotallog int    `json:"appfirewalltotallog,omitempty"`
	/**
	* Total number of security check log messages generated by the Application Firewall.
	 */
	Appfirewalllograte   float64 `json:"appfirewalllograte,omitempty"`
	Appfirewalltotalviol int     `json:"appfirewalltotalviol,omitempty"`
	/**
	* Total number of security check violations seen by the Application Firewall.
	 */
	Appfirewallviolrate         float64 `json:"appfirewallviolrate,omitempty"`
	Appfirewallshortavgresptime int     `json:"appfirewallshortavgresptime,omitempty"`
	Appfirewalllongavgresptime  int     `json:"appfirewalllongavgresptime,omitempty"`
	Appfirewallrequests         int     `json:"appfirewallrequests,omitempty"`
	/**
	* HTTP/HTTPS requests sent to your protected web servers via the Application Firewall.
	 */
	Appfirewallrequestsrate float64 `json:"appfirewallrequestsrate,omitempty"`
	Appfirewallreqbytes     int     `json:"appfirewallreqbytes,omitempty"`
	/**
	* Number of bytes transfered for requests
	 */
	Appfirewallreqbytesrate float64 `json:"appfirewallreqbytesrate,omitempty"`
	Appfirewallresponses    []int   `json:"appfirewallresponses,omitempty"`
	/**
	* HTTP/HTTPS responses sent by your protected web servers via the Application Firewall.
	 */
	Appfirewallresponsesrate float64 `json:"appfirewallresponsesrate,omitempty"`
	Appfirewallresbytes      int     `json:"appfirewallresbytes,omitempty"`
	/**
	* Number of bytes transfered for responses
	 */
	Appfirewallresbytesrate float64 `json:"appfirewallresbytesrate,omitempty"`
	Appfirewallaborts       int     `json:"appfirewallaborts,omitempty"`
	/**
	* Incomplete HTTP/HTTPS requests aborted by the client before the Application Firewall could finish processing them.
	 */
	Appfirewallabortsrate float64 `json:"appfirewallabortsrate,omitempty"`
	Appfirewallredirects  int     `json:"appfirewallredirects,omitempty"`
	/**
	* HTTP/HTTPS requests redirected by the Application Firewall to a different Web page or web server. (HTTP 302)
	 */
	Appfirewallredirectsrate float64 `json:"appfirewallredirectsrate,omitempty"`
	Appfirewalltrapsdropped  int     `json:"appfirewalltrapsdropped,omitempty"`
	Appfirewallviolstarturl  int     `json:"appfirewallviolstarturl,omitempty"`
	/**
	* Number of Start URL security check violations seen by the Application Firewall.
	 */
	Appfirewallviolstarturlrate float64 `json:"appfirewallviolstarturlrate,omitempty"`
	Appfirewallvioldenyurl      int     `json:"appfirewallvioldenyurl,omitempty"`
	/**
	* Number of Deny URL security check violations seen by the Application Firewall.
	 */
	Appfirewallvioldenyurlrate   float64 `json:"appfirewallvioldenyurlrate,omitempty"`
	Appfirewallviolrefererheader int     `json:"appfirewallviolrefererheader,omitempty"`
	/**
	* Number of Referer Header security check violations seen by the Application Firewall.
	 */
	Appfirewallviolrefererheaderrate float64 `json:"appfirewallviolrefererheaderrate,omitempty"`
	Appfirewallviolbufferoverflow    int     `json:"appfirewallviolbufferoverflow,omitempty"`
	/**
	* Number of Buffer Overflow security check violations seen by the Application Firewall.
	 */
	Appfirewallviolbufferoverflowrate  float64 `json:"appfirewallviolbufferoverflowrate,omitempty"`
	Appfirewallpostbodylimitviolations int     `json:"appfirewallpostbodylimitviolations,omitempty"`
	/**
	* Number of Post Body Limit security check violations seen by the Application Firewall.
	 */
	Appfirewallpostbodylimitviolationsrate float64 `json:"appfirewallpostbodylimitviolationsrate,omitempty"`
	Appfirewallviolcookie                  int     `json:"appfirewallviolcookie,omitempty"`
	/**
	* Number of Cookie Consistency security check violations seen by the Application Firewall.
	 */
	Appfirewallviolcookierate   float64 `json:"appfirewallviolcookierate,omitempty"`
	Appfirewallviolcookiehijack int     `json:"appfirewallviolcookiehijack,omitempty"`
	/**
	* Number of Cookie Hijacking security violations seen by the Application Firewall.
	 */
	Appfirewallviolcookiehijackrate float64 `json:"appfirewallviolcookiehijackrate,omitempty"`
	Appfirewallviolcsrftag          int     `json:"appfirewallviolcsrftag,omitempty"`
	/**
	* Number of Cross Site Request Forgery form tag security check violations seen by the Application Firewall.
	 */
	Appfirewallviolcsrftagrate float64 `json:"appfirewallviolcsrftagrate,omitempty"`
	Appfirewallviolxss         int     `json:"appfirewallviolxss,omitempty"`
	/**
	* Number of HTML Cross-Site Scripting security check violations seen by the Application Firewall.
	 */
	Appfirewallviolxssrate float64 `json:"appfirewallviolxssrate,omitempty"`
	Appfirewallviolsql     int     `json:"appfirewallviolsql,omitempty"`
	/**
	* Number of HTML SQL Injection security check violations seen by the Application Firewall.
	 */
	Appfirewallviolsqlrate     float64 `json:"appfirewallviolsqlrate,omitempty"`
	Appfirewallviolfieldformat int     `json:"appfirewallviolfieldformat,omitempty"`
	/**
	* Number of Field Format security check violations seen by the Application Firewall.
	 */
	Appfirewallviolfieldformatrate  float64 `json:"appfirewallviolfieldformatrate,omitempty"`
	Appfirewallviolfieldconsistency int     `json:"appfirewallviolfieldconsistency,omitempty"`
	/**
	* Number of Field Consistency security check violations seen by the Application Firewall.
	 */
	Appfirewallviolfieldconsistencyrate float64 `json:"appfirewallviolfieldconsistencyrate,omitempty"`
	Appfirewallviolfileuploadtypes      int     `json:"appfirewallviolfileuploadtypes,omitempty"`
	/**
	* Number of Field Upload Types security check violations seen by the Application Firewall.
	 */
	Appfirewallviolfileuploadtypesrate           float64 `json:"appfirewallviolfileuploadtypesrate,omitempty"`
	Appfirewallviolxmlpayloadcontenttypemismatch int     `json:"appfirewallviolxmlpayloadcontenttypemismatch,omitempty"`
	/**
	* Number of Mismatched Content-Type in request with XML Payload security check violations seen by the Application Firewall.
	 */
	Appfirewallviolxmlpayloadcontenttypemismatchrate float64 `json:"appfirewallviolxmlpayloadcontenttypemismatchrate,omitempty"`
	Appfirewallviolcreditcard                        int     `json:"appfirewallviolcreditcard,omitempty"`
	/**
	* Number of Credit Card security check violations seen by the Application Firewall.
	 */
	Appfirewallviolcreditcardrate float64 `json:"appfirewallviolcreditcardrate,omitempty"`
	Appfirewallviolsafeobject     int     `json:"appfirewallviolsafeobject,omitempty"`
	/**
	* Number of Safe Object security check violations seen by the Application Firewall.
	 */
	Appfirewallviolsafeobjectrate float64 `json:"appfirewallviolsafeobjectrate,omitempty"`
	Appfirewallviolsignature      int     `json:"appfirewallviolsignature,omitempty"`
	/**
	* Number of Signature violations seen by the Application Firewall.
	 */
	Appfirewallviolsignaturerate float64 `json:"appfirewallviolsignaturerate,omitempty"`
	Appfirewallviolcontenttype   int     `json:"appfirewallviolcontenttype,omitempty"`
	/**
	* Number of Content type security check violations seen by the Application Firewall.
	 */
	Appfirewallviolcontenttyperate float64 `json:"appfirewallviolcontenttyperate,omitempty"`
	Appfirewallviolcmd             int     `json:"appfirewallviolcmd,omitempty"`
	/**
	* Number of HTML CMD Injection security check violations seen by the Application Firewall.
	 */
	Appfirewallviolcmdrate float64 `json:"appfirewallviolcmdrate,omitempty"`
	Appfirewallvioljsondos int     `json:"appfirewallvioljsondos,omitempty"`
	/**
	* Number of JSON Denial-of-Service security check violations seen by the Application Firewall.
	 */
	Appfirewallvioljsondosrate float64 `json:"appfirewallvioljsondosrate,omitempty"`
	Appfirewallvioljsonsql     int     `json:"appfirewallvioljsonsql,omitempty"`
	/**
	* Number of JSON SQL Injection security check violations seen by the Application Firewall.
	 */
	Appfirewallvioljsonsqlrate float64 `json:"appfirewallvioljsonsqlrate,omitempty"`
	Appfirewallvioljsonxss     int     `json:"appfirewallvioljsonxss,omitempty"`
	/**
	* Number of JSON Cross-Site Scripting (XSS) security check violations seen by the Application Firewall.
	 */
	Appfirewallvioljsonxssrate float64 `json:"appfirewallvioljsonxssrate,omitempty"`
	Appfirewallvioljsoncmd     int     `json:"appfirewallvioljsoncmd,omitempty"`
	/**
	* Number of JSON Command Injection security check violations seen by the Application Firewall.
	 */
	Appfirewallvioljsoncmdrate              float64 `json:"appfirewallvioljsoncmdrate,omitempty"`
	Appfirewallviolwellformednessviolations int     `json:"appfirewallviolwellformednessviolations,omitempty"`
	/**
	* Number of XML Format security check violations seen by the Application Firewall.
	 */
	Appfirewallviolwellformednessviolationsrate float64 `json:"appfirewallviolwellformednessviolationsrate,omitempty"`
	Appfirewallviolxdosviolations               int     `json:"appfirewallviolxdosviolations,omitempty"`
	/**
	* Number of XML Denial-of-Service security check violations seen by the Application Firewall.
	 */
	Appfirewallviolxdosviolationsrate float64 `json:"appfirewallviolxdosviolationsrate,omitempty"`
	Appfirewallviolmsgvalviolations   int     `json:"appfirewallviolmsgvalviolations,omitempty"`
	/**
	* Number of XML Message Validation security check violations seen by the Application Firewall.
	 */
	Appfirewallviolmsgvalviolationsrate float64 `json:"appfirewallviolmsgvalviolationsrate,omitempty"`
	Appfirewallviolwsiviolations        int     `json:"appfirewallviolwsiviolations,omitempty"`
	/**
	* Number of Web Services Interoperability (WS-I) security check violations seen by the Application Firewall.
	 */
	Appfirewallviolwsiviolationsrate float64 `json:"appfirewallviolwsiviolationsrate,omitempty"`
	Appfirewallviolxmlsqlviolations  int     `json:"appfirewallviolxmlsqlviolations,omitempty"`
	/**
	* Number of XML SQL Injection security check violations seen by the Application Firewall.
	 */
	Appfirewallviolxmlsqlviolationsrate float64 `json:"appfirewallviolxmlsqlviolationsrate,omitempty"`
	Appfirewallviolxmlxssviolations     int     `json:"appfirewallviolxmlxssviolations,omitempty"`
	/**
	* Number of XML Cross-Site Scripting (XSS) security check violations seen by the Application Firewall.
	 */
	Appfirewallviolxmlxssviolationsrate    float64 `json:"appfirewallviolxmlxssviolationsrate,omitempty"`
	Appfirewallviolxmlattachmentviolations int     `json:"appfirewallviolxmlattachmentviolations,omitempty"`
	/**
	* Number of XML Attachment security check violations seen by the Application Firewall.
	 */
	Appfirewallviolxmlattachmentviolationsrate float64 `json:"appfirewallviolxmlattachmentviolationsrate,omitempty"`
	Appfirewallviolxmlsoapfaultviolations      int     `json:"appfirewallviolxmlsoapfaultviolations,omitempty"`
	/**
	* Number of requests returning soap:fault from the backend server
	 */
	Appfirewallviolxmlsoapfaultviolationsrate float64 `json:"appfirewallviolxmlsoapfaultviolationsrate,omitempty"`
	Appfirewallviolxmlgenviolations           int     `json:"appfirewallviolxmlgenviolations,omitempty"`
	/**
	* Number of requests returning XML generic error from the backend server
	 */
	Appfirewallviolxmlgenviolationsrate float64 `json:"appfirewallviolxmlgenviolationsrate,omitempty"`
	Appfirewallviolsqlgram              int     `json:"appfirewallviolsqlgram,omitempty"`
	/**
	* Number of HTML SQL Injection security check violations (using SQL grammar) seen by the Application Firewall.
	 */
	Appfirewallviolsqlgramrate float64 `json:"appfirewallviolsqlgramrate,omitempty"`
	Appfirewallvioljsonsqlgram int     `json:"appfirewallvioljsonsqlgram,omitempty"`
	/**
	* Number of JSON SQL Injection security check violations (reported using SQL grammar) seen by the Application Firewall.
	 */
	Appfirewallvioljsonsqlgramrate float64 `json:"appfirewallvioljsonsqlgramrate,omitempty"`
	Appfirewalllogstarturl         int     `json:"appfirewalllogstarturl,omitempty"`
	/**
	* Number of Start URL security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogstarturlrate float64 `json:"appfirewalllogstarturlrate,omitempty"`
	Appfirewalllogdenyurl      int     `json:"appfirewalllogdenyurl,omitempty"`
	/**
	* Number of Deny URL security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogdenyurlrate   float64 `json:"appfirewalllogdenyurlrate,omitempty"`
	Appfirewalllogrefererheader int     `json:"appfirewalllogrefererheader,omitempty"`
	/**
	* Number of Referer Header security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogrefererheaderrate float64 `json:"appfirewalllogrefererheaderrate,omitempty"`
	Appfirewalllogbufferoverflow    int     `json:"appfirewalllogbufferoverflow,omitempty"`
	/**
	* Number of Buffer Overflow security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogbufferoverflowrate float64 `json:"appfirewalllogbufferoverflowrate,omitempty"`
	Appfirewallpostbodylimitlogs     int     `json:"appfirewallpostbodylimitlogs,omitempty"`
	/**
	* Number of Post Body Limit security check logs seen by the Application Firewall.
	 */
	Appfirewallpostbodylimitlogsrate float64 `json:"appfirewallpostbodylimitlogsrate,omitempty"`
	Appfirewalllogcookie             int     `json:"appfirewalllogcookie,omitempty"`
	/**
	* Number of Cookie Consistency security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogcookierate   float64 `json:"appfirewalllogcookierate,omitempty"`
	Appfirewalllogcookiehijack int     `json:"appfirewalllogcookiehijack,omitempty"`
	/**
	* Number of Cookie Hijacking security violation log messages generated by the Application Firewall.
	 */
	Appfirewalllogcookiehijackrate float64 `json:"appfirewalllogcookiehijackrate,omitempty"`
	Appfirewalllogcsrftag          int     `json:"appfirewalllogcsrftag,omitempty"`
	/**
	* Number of Cross Site Request Forgery form tag security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogcsrftagrate float64 `json:"appfirewalllogcsrftagrate,omitempty"`
	Appfirewalllogxss         int     `json:"appfirewalllogxss,omitempty"`
	/**
	* Number of HTML Cross-Site Scripting security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogxssrate      float64 `json:"appfirewalllogxssrate,omitempty"`
	Appfirewalllogtransformxss int     `json:"appfirewalllogtransformxss,omitempty"`
	/**
	* Number of HTML Cross-Site Scripting security check transform log messages generated by the Application Firewall.
	 */
	Appfirewalllogtransformxssrate float64 `json:"appfirewalllogtransformxssrate,omitempty"`
	Appfirewalllogsql              int     `json:"appfirewalllogsql,omitempty"`
	/**
	* Number of HTML SQL Injection security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogsqlrate      float64 `json:"appfirewalllogsqlrate,omitempty"`
	Appfirewalllogtransformsql int     `json:"appfirewalllogtransformsql,omitempty"`
	/**
	* Number of HTML SQL Injection security check transform log messages generated by the Application Firewall.
	 */
	Appfirewalllogtransformsqlrate float64 `json:"appfirewalllogtransformsqlrate,omitempty"`
	Appfirewalllogfieldformat      int     `json:"appfirewalllogfieldformat,omitempty"`
	/**
	* Number of Field Format security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogfieldformatrate  float64 `json:"appfirewalllogfieldformatrate,omitempty"`
	Appfirewalllogfieldconsistency int     `json:"appfirewalllogfieldconsistency,omitempty"`
	/**
	* Number of Field Consistency security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogfieldconsistencyrate float64 `json:"appfirewalllogfieldconsistencyrate,omitempty"`
	Appfirewalllogcreditcard           int     `json:"appfirewalllogcreditcard,omitempty"`
	/**
	* Number of Credit Card security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogcreditcardrate float64 `json:"appfirewalllogcreditcardrate,omitempty"`
	Appfirewalllogsafeobject     int     `json:"appfirewalllogsafeobject,omitempty"`
	/**
	* Number of Safe Object security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogsafeobjectrate float64 `json:"appfirewalllogsafeobjectrate,omitempty"`
	Appfirewallsignaturelogs     int     `json:"appfirewallsignaturelogs,omitempty"`
	/**
	* Number of Signature logs generated by the Application Firewall.
	 */
	Appfirewallsignaturelogsrate float64 `json:"appfirewallsignaturelogsrate,omitempty"`
	Appfirewalllogcontenttype    int     `json:"appfirewalllogcontenttype,omitempty"`
	/**
	* Number of content type security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogcontenttyperate float64 `json:"appfirewalllogcontenttyperate,omitempty"`
	Appfirewalllogsjsondos        int     `json:"appfirewalllogsjsondos,omitempty"`
	/**
	* Number of JSON Denial-of-Service security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogsjsondosrate float64 `json:"appfirewalllogsjsondosrate,omitempty"`
	Appfirewalllogsjsonsql     int     `json:"appfirewalllogsjsonsql,omitempty"`
	/**
	* Number of JSON SQL Injection security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogsjsonsqlrate float64 `json:"appfirewalllogsjsonsqlrate,omitempty"`
	Appfirewalllogsjsonxss     int     `json:"appfirewalllogsjsonxss,omitempty"`
	/**
	* Number of JSON Cross-Site Scripting (XSS) security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogsjsonxssrate float64 `json:"appfirewalllogsjsonxssrate,omitempty"`
	Appfirewalllogsjsoncmd     int     `json:"appfirewalllogsjsoncmd,omitempty"`
	/**
	* Number of JSON Command Injection security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogsjsoncmdrate    float64 `json:"appfirewalllogsjsoncmdrate,omitempty"`
	Appfirewalllogfileuploadtypes int     `json:"appfirewalllogfileuploadtypes,omitempty"`
	/**
	* Number of File Upload Types security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogfileuploadtypesrate           float64 `json:"appfirewalllogfileuploadtypesrate,omitempty"`
	Appfirewalllogxmlpayloadcontenttypemismatch int     `json:"appfirewalllogxmlpayloadcontenttypemismatch,omitempty"`
	/**
	* Number of Mismatched Content-Type in request with XML Payload security check logs seen by the Application Firewall.
	 */
	Appfirewalllogxmlpayloadcontenttypemismatchrate float64 `json:"appfirewalllogxmlpayloadcontenttypemismatchrate,omitempty"`
	Appfirewalllogcmd                               int     `json:"appfirewalllogcmd,omitempty"`
	/**
	* Number of HTML Command Injection security check log messages generated by the Application Firewall.
	 */
	Appfirewalllogcmdrate         float64 `json:"appfirewalllogcmdrate,omitempty"`
	Appfirewallwellformednesslogs int     `json:"appfirewallwellformednesslogs,omitempty"`
	/**
	* Number of XML Format security check log messages generated by the Application Firewall.
	 */
	Appfirewallwellformednesslogsrate float64 `json:"appfirewallwellformednesslogsrate,omitempty"`
	Appfirewallxdoslogs               int     `json:"appfirewallxdoslogs,omitempty"`
	/**
	* Number of XML Denial-of-Service security check log messages generated by the Application Firewall.
	 */
	Appfirewallxdoslogsrate float64 `json:"appfirewallxdoslogsrate,omitempty"`
	Appfirewallmsgvallogs   int     `json:"appfirewallmsgvallogs,omitempty"`
	/**
	* Number of XML Message Validation security check log messages generated by the Application Firewall.
	 */
	Appfirewallmsgvallogsrate float64 `json:"appfirewallmsgvallogsrate,omitempty"`
	Appfirewallwsilogs        int     `json:"appfirewallwsilogs,omitempty"`
	/**
	* Number of Web Services Interoperability (WS-I) security check log messages generated by the Application Firewall.
	 */
	Appfirewallwsilogsrate float64 `json:"appfirewallwsilogsrate,omitempty"`
	Appfirewallxmlsqllogs  int     `json:"appfirewallxmlsqllogs,omitempty"`
	/**
	* Number of XML SQL Injection security check log messages generated by the Application Firewall.
	 */
	Appfirewallxmlsqllogsrate float64 `json:"appfirewallxmlsqllogsrate,omitempty"`
	Appfirewallxmlxsslogs     int     `json:"appfirewallxmlxsslogs,omitempty"`
	/**
	* Number of XML Cross-Site Scripting (XSS) security check log messages generated by the Application Firewall.
	 */
	Appfirewallxmlxsslogsrate    float64 `json:"appfirewallxmlxsslogsrate,omitempty"`
	Appfirewallxmlattachmentlogs int     `json:"appfirewallxmlattachmentlogs,omitempty"`
	/**
	* Number of XML Attachment security check log messages generated by the Application Firewall.
	 */
	Appfirewallxmlattachmentlogsrate float64 `json:"appfirewallxmlattachmentlogsrate,omitempty"`
	Appfirewallxmlsoapfaultlogs      int     `json:"appfirewallxmlsoapfaultlogs,omitempty"`
	/**
	* Number of requests generating soap:fault log messages
	 */
	Appfirewallxmlsoapfaultlogsrate float64 `json:"appfirewallxmlsoapfaultlogsrate,omitempty"`
	Appfirewallxmlgenlogs           int     `json:"appfirewallxmlgenlogs,omitempty"`
	/**
	* Number of requests generating XML generic error log messages
	 */
	Appfirewallxmlgenlogsrate float64 `json:"appfirewallxmlgenlogsrate,omitempty"`
	Appfirewalllogsqlgram     int     `json:"appfirewalllogsqlgram,omitempty"`
	/**
	* Number of HTML SQL Injection security check log messages (reported by SQL grammar) generated by the Application Firewall.
	 */
	Appfirewalllogsqlgramrate  float64 `json:"appfirewalllogsqlgramrate,omitempty"`
	Appfirewalllogsjsonsqlgram int     `json:"appfirewalllogsjsonsqlgram,omitempty"`
	/**
	* Number of JSON SQL Injection security check log messages (reported by SQL grammar) generated by the Application Firewall.
	 */
	Appfirewalllogsjsonsqlgramrate float64 `json:"appfirewalllogsjsonsqlgramrate,omitempty"`
	Appfirewallret4xx              int     `json:"appfirewallret4xx,omitempty"`
	/**
	* Number of requests returning HTTP 4xx from the backend server
	 */
	Appfirewallret4xxrate float64 `json:"appfirewallret4xxrate,omitempty"`
	Appfirewallret5xx     int     `json:"appfirewallret5xx,omitempty"`
	/**
	* Number of requests returning HTTP 5xx from the backend server
	 */
	Appfirewallret5xxrate float64 `json:"appfirewallret5xxrate,omitempty"`
}
